In [ ]:
## 1. Import pandas to use to load and analyze dataset
import pandas as pd

In [ ]:
## import dataset on pandas
df = pd.read_csv("C:/Users/MY PC/OneDrive/Documents/customer_sales_300k/customer_sales_300k_customers.csv")

In [ ]:
## Checked to see if it loaded... its loaded
df.head()

,Customer_ID,Order_ID,Order_Date,Product_Category,Product_Name,Region,Quantity,Unit_Price,Revenue
0,CUST121959,ORD0000000,21-04-25,Office Supplies,Smartphone,Abuja,1,129074,129074
1,CUST146868,ORD0000001,22-06-23,Electronics,Laptop,Lagos,3,96966,290898
2,CUST131933,ORD0000002,22-12-25,Electronics,Tablet,Kano,2,38408,76816
3,CUST259179,ORD0000003,02-08-25,Electronics,Tablet,Rivers,5,101602,508010
4,CUST119880,ORD0000004,30-11-25,Electronics,Desk,Enugu,4,236993,947972

In [ ]:
## Checked dymension of data to know how many rows and columns
df.shape

(100000, 9)

In [ ]:
## Names of the columns
df.columns

Index(['Customer_ID', 'Order_ID', 'Order_Date', 'Product_Category',
       'Product_Name', 'Region', 'Quantity', 'Unit_Price', 'Revenue'],
      dtype='object')

In [ ]:
## Summarized info about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Customer_ID       100000 non-null  object
 1   Order_ID          100000 non-null  object
 2   Order_Date        100000 non-null  object
 3   Product_Category  100000 non-null  object
 4   Product_Name      100000 non-null  object
 5   Region            100000 non-null  object
 6   Quantity          100000 non-null  int64
 7   Unit_Price        100000 non-null  int64
 8   Revenue           100000 non-null  int64
dtypes: int64(3), object(6)
memory usage: 6.9+ MB

In [ ]:
## A description of the dataset following certain standard calculations
df.describe()

            Quantity     Unit_Price       Revenue
count  100000.000000  100000.000000  1.000000e+05
mean        2.994710  152025.400970  4.565183e+05
std         1.414808   85230.520222  3.561893e+05
min         1.000000    5002.000000  5.011000e+03
25%         2.000000   78071.000000  1.702635e+05
50%         3.000000  151454.500000  3.572610e+05
75%         4.000000  226187.250000  6.782210e+05
max         5.000000  299993.000000  1.499885e+06

In [ ]:
## Clean the columns
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [ ]:
## Columns cleaned
df.columns

Index(['customer_id', 'order_id', 'order_date', 'product_category',
       'product_name', 'region', 'quantity', 'unit_price', 'revenue'],
      dtype='object')

In [ ]:
#Fix date column to YYYY-MM-DD format
df['order_date'] = pd.to_datetime(df['order_date'])

C:\Users\MY PC\AppData\Local\Temp\ipykernel_19108\3794471090.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['order_date'] = pd.to_datetime(df['order_date'])

In [ ]:
## Checked to see that it worked
df.head()

,customer_id,order_id,order_date,product_category,product_name,region,quantity,unit_price,revenue
0,CUST121959,ORD0000000,2025-04-21,Office Supplies,Smartphone,Abuja,1,129074,129074
1,CUST146868,ORD0000001,2023-06-22,Electronics,Laptop,Lagos,3,96966,290898
2,CUST131933,ORD0000002,2025-12-22,Electronics,Tablet,Kano,2,38408,76816
3,CUST259179,ORD0000003,2025-02-08,Electronics,Tablet,Rivers,5,101602,508010
4,CUST119880,ORD0000004,2025-11-30,Electronics,Desk,Enugu,4,236993,947972

In [24]:
## Create time features
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name

In [26]:
## Create revenue column
df['revenue'] = df['quantity'] * df['unit_price']

In [28]:
## Check for missing values
df.duplicated().sum()

np.int64(0)

In [ ]:
## code to rune if duplicate exists but none here
df = df.drop_duplicates()

In [30]:
## Revenue by category
df.groupby('product_category')['revenue'].sum().sort_values(ascending=False)

product_category
Fashion            11489871510
Electronics        11474958678
Office Supplies    11364182707
Home Appliances    11322816449
Name: revenue, dtype: int64

In [32]:
## Revenue by states
df.groupby('region')['revenue'].sum().sort_values(ascending=False)

region
Enugu            6632947560
Rivers           6578061126
Ibadan           6571548310
Abuja            6493863763
Kano             6490371068
Port Harcourt    6467263133
Lagos            6417774384
Name: revenue, dtype: int64

In [ ]:
## Monthly trend
df.groupby(['year', 'month'])['revenue'].sum()

year  month
2021  1        823243895
      2        701983173
      3        734215357
      4        729615165
      5        765174463
      6        748708782
      7        742259439
      8        783760418
      9        752943463
      10       788592723
      11       732219440
      12       773896266
2022  1        783990446
      2        711867086
      3        770849604
      4        793902101
      5        779648445
      6        784993749
      7        778257839
      8        763556535
      9        756625916
      10       761607040
      11       737502032
      12       760032885
2023  1        774993631
      2        711456151
      3        768000764
      4        776031967
      5        787697802
      6        746708022
      7        785958338
      8        769834159
      9        725363546
      10       733335645
      11       754952993
      12       740488118
2024  1        787839270
      2        756777488
      3        782054014
      4        739848436
      5        763972864
      6        695949173
      7        755529818
      8        748368652
      9        736064055
      10       785647268
      11       768471380
      12       783851894
2025  1        785577850
      2        705101778
      3        752595261
      4        751863355
      5        750097661
      6        785974669
      7        777162079
      8        780830060
      9        775084816
      10       761923173
      11       773020860
      12       813956072
Name: revenue, dtype: int64

In [ ]:
## Export the cleaned data for SQL and Tableau
df.to_csv("cleaned_sales_data.csv", index=False)

In [ ]:
## 2. Advanced Analysis Begins
## Customer value analysis to identify high-value customers and measuring customer lifetime value
customer_value = (
    df.groupby('customer_id')
    .agg(
        total_revenue=('revenue', 'sum'),
        total_orders=('order_id', 'nunique')
    )
    .sort_values(by='total_revenue', ascending=False)
)

customer_value.head()

             total_revenue  total_orders
customer_id
CUST196823         3610529             4
CUST014829         3486876             4
CUST083519         3412968             4
CUST133426         3394039             4
CUST142322         3379305             3

In [39]:
## Create customer segment
customer_value['segment'] = pd.qcut(
    customer_value['total_revenue'],
    q=4,
    labels=['Low', 'Mid', 'High', 'VIP']
)

In [44]:
## Revenue by segment
customer_value.groupby('segment')['total_revenue'].sum()

C:\Users\MY PC\AppData\Local\Temp\ipykernel_19108\4217191452.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customer_value.groupby('segment')['total_revenue'].sum()

segment
Low      2215654075
Mid      6347277614
High    12576251793
VIP     24512645862
Name: total_revenue, dtype: int64

In [ ]:
## Merge back to main daaset
df =  df.merge(customer_value[['segment']],
on='customer_id', how='left')


## Dataset now has trasaction data and customer segment

In [ ]:
## Ivnvestigate product performance to discover high revenue associated with low orders and high orders with low revenue
## Prduct category's revenue and num_orders
product_perf = (
    df.groupby('product_category')
    .agg(
        revenue=('revenue', 'sum'),
        orders=('order_id', 'count')
    )
    .sort_values(by='revenue', ascending=False)
)
product_perf

                      revenue  orders
product_category
Fashion           11489871510   25115
Electronics       11474958678   25067
Office Supplies   11364182707   24948
Home Appliances   11322816449   24870

In [55]:
## Regional performance to find out underperforming states
region_perf = (
    df.groupby('region')['revenue']
    .sum()
    .sort_values(ascending=False)
)
region_perf

region
Enugu            6632947560
Rivers           6578061126
Ibadan           6571548310
Abuja            6493863763
Kano             6490371068
Port Harcourt    6467263133
Lagos            6417774384
Name: revenue, dtype: int64

In [ ]:
## Time analysis - Used for line chart in Tableau
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month

monthly_trend = (
    df.groupby(['year', 'month']) ['revenue']
    .sum()
    .reset_index()
)

In [58]:
## Export finalized sale dataset
df.to_csv('final_sales_dataset.csv', index=False)

KEY INSIGHTS

1. Revenue Concentration

In [59]:
customer_value.groupby('segment')['total_revenue'].sum()

C:\Users\MY PC\AppData\Local\Temp\ipykernel_19108\2183801404.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  customer_value.groupby('segment')['total_revenue'].sum()

segment
Low      2215654075
Mid      6347277614
High    12576251793
VIP     24512645862
Name: total_revenue, dtype: int64

VIP = majority of revenue

2. Top Performing Categories

In [60]:
product_perf

                      revenue  orders
product_category
Fashion           11489871510   25115
Electronics       11474958678   25067
Office Supplies   11364182707   24948
Home Appliances   11322816449   24870

Fashion category generates the most revenue
Home appliances category has the lowest revenue with the lowest order

3. Regional Insights

In [65]:
region_perf.head(7)
region_perf.tail(7)

region
Enugu            6632947560
Rivers           6578061126
Ibadan           6571548310
Abuja            6493863763
Kano             6490371068
Port Harcourt    6467263133
Lagos            6417774384
Name: revenue, dtype: int64

Enugu is the best-performing state with NGN 6,632,947,560.00
Lagos is the least-performing state with NGN 6,417,774,384.00

4. Trend Insights

In [68]:
monthly_trend.head(12)

    year  month    revenue
0   2021      1  823243895
1   2021      2  701983173
2   2021      3  734215357
3   2021      4  729615165
4   2021      5  765174463
5   2021      6  748708782
6   2021      7  742259439
7   2021      8  783760418
8   2021      9  752943463
9   2021     10  788592723
10  2021     11  732219440
11  2021     12  773896266

Is revenue increasing?
Any seasonal spikes?

💡BUSINESS INSIGHTS

🌍 Revenue is heavily concentrated amond VIP customers, indicating dependeance of high-value buyers.

🌍 Electronics drives the highest revenue, while other categories underperform.

🌍 Lagos and Abuja dominates sales, while some regions show weak performance.

🌍 Monthly trends shows fluctuation, suggesting potential seasonality.

🚀RECOMMENDATIONS

🌍 Focus retention strategies for VIP customers.

🌍 Increase marketing in underperforming regions.

🌍 Expand inventory in top-performing categories.

🌍 Introduce promotions during low-revenue months.